# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bryanc/devel/vwm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bryanc/devel/vwm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryanc/devel/vwm/CMakeFiles /home/bryanc/devel/vwm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bryanc/devel/vwm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vwm

# Build rule for target.
vwm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vwm
.PHONY : vwm

# fast build rule for target.
vwm/fast:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/build
.PHONY : vwm/fast

# Manual pre-install relink rule for target.
vwm/preinstall:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/preinstall
.PHONY : vwm/preinstall

bkgd.o: bkgd.c.o

.PHONY : bkgd.o

# target to build an object file
bkgd.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/bkgd.c.o
.PHONY : bkgd.c.o

bkgd.i: bkgd.c.i

.PHONY : bkgd.i

# target to preprocess a source file
bkgd.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/bkgd.c.i
.PHONY : bkgd.c.i

bkgd.s: bkgd.c.s

.PHONY : bkgd.s

# target to generate assembly for a file
bkgd.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/bkgd.c.s
.PHONY : bkgd.c.s

clock.o: clock.c.o

.PHONY : clock.o

# target to build an object file
clock.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/clock.c.o
.PHONY : clock.c.o

clock.i: clock.c.i

.PHONY : clock.i

# target to preprocess a source file
clock.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/clock.c.i
.PHONY : clock.c.i

clock.s: clock.c.s

.PHONY : clock.s

# target to generate assembly for a file
clock.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/clock.c.s
.PHONY : clock.c.s

hotkeys.o: hotkeys.c.o

.PHONY : hotkeys.o

# target to build an object file
hotkeys.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/hotkeys.c.o
.PHONY : hotkeys.c.o

hotkeys.i: hotkeys.c.i

.PHONY : hotkeys.i

# target to preprocess a source file
hotkeys.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/hotkeys.c.i
.PHONY : hotkeys.c.i

hotkeys.s: hotkeys.c.s

.PHONY : hotkeys.s

# target to generate assembly for a file
hotkeys.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/hotkeys.c.s
.PHONY : hotkeys.c.s

mainmenu.o: mainmenu.c.o

.PHONY : mainmenu.o

# target to build an object file
mainmenu.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/mainmenu.c.o
.PHONY : mainmenu.c.o

mainmenu.i: mainmenu.c.i

.PHONY : mainmenu.i

# target to preprocess a source file
mainmenu.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/mainmenu.c.i
.PHONY : mainmenu.c.i

mainmenu.s: mainmenu.c.s

.PHONY : mainmenu.s

# target to generate assembly for a file
mainmenu.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/mainmenu.c.s
.PHONY : mainmenu.c.s

modules.o: modules.c.o

.PHONY : modules.o

# target to build an object file
modules.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/modules.c.o
.PHONY : modules.c.o

modules.i: modules.c.i

.PHONY : modules.i

# target to preprocess a source file
modules.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/modules.c.i
.PHONY : modules.c.i

modules.s: modules.c.s

.PHONY : modules.s

# target to generate assembly for a file
modules.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/modules.c.s
.PHONY : modules.c.s

poll_input_thd.o: poll_input_thd.c.o

.PHONY : poll_input_thd.o

# target to build an object file
poll_input_thd.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/poll_input_thd.c.o
.PHONY : poll_input_thd.c.o

poll_input_thd.i: poll_input_thd.c.i

.PHONY : poll_input_thd.i

# target to preprocess a source file
poll_input_thd.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/poll_input_thd.c.i
.PHONY : poll_input_thd.c.i

poll_input_thd.s: poll_input_thd.c.s

.PHONY : poll_input_thd.s

# target to generate assembly for a file
poll_input_thd.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/poll_input_thd.c.s
.PHONY : poll_input_thd.c.s

private.o: private.c.o

.PHONY : private.o

# target to build an object file
private.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/private.c.o
.PHONY : private.c.o

private.i: private.c.i

.PHONY : private.i

# target to preprocess a source file
private.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/private.c.i
.PHONY : private.c.i

private.s: private.c.s

.PHONY : private.s

# target to generate assembly for a file
private.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/private.c.s
.PHONY : private.c.s

profile.o: profile.c.o

.PHONY : profile.o

# target to build an object file
profile.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/profile.c.o
.PHONY : profile.c.o

profile.i: profile.c.i

.PHONY : profile.i

# target to preprocess a source file
profile.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/profile.c.i
.PHONY : profile.c.i

profile.s: profile.c.s

.PHONY : profile.s

# target to generate assembly for a file
profile.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/profile.c.s
.PHONY : profile.c.s

settings.o: settings.c.o

.PHONY : settings.o

# target to build an object file
settings.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/settings.c.o
.PHONY : settings.c.o

settings.i: settings.c.i

.PHONY : settings.i

# target to preprocess a source file
settings.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/settings.c.i
.PHONY : settings.c.i

settings.s: settings.c.s

.PHONY : settings.s

# target to generate assembly for a file
settings.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/settings.c.s
.PHONY : settings.c.s

signals.o: signals.c.o

.PHONY : signals.o

# target to build an object file
signals.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/signals.c.o
.PHONY : signals.c.o

signals.i: signals.c.i

.PHONY : signals.i

# target to preprocess a source file
signals.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/signals.c.i
.PHONY : signals.c.i

signals.s: signals.c.s

.PHONY : signals.s

# target to generate assembly for a file
signals.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/signals.c.s
.PHONY : signals.c.s

sleep_thd.o: sleep_thd.c.o

.PHONY : sleep_thd.o

# target to build an object file
sleep_thd.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/sleep_thd.c.o
.PHONY : sleep_thd.c.o

sleep_thd.i: sleep_thd.c.i

.PHONY : sleep_thd.i

# target to preprocess a source file
sleep_thd.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/sleep_thd.c.i
.PHONY : sleep_thd.c.i

sleep_thd.s: sleep_thd.c.s

.PHONY : sleep_thd.s

# target to generate assembly for a file
sleep_thd.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/sleep_thd.c.s
.PHONY : sleep_thd.c.s

strings.o: strings.c.o

.PHONY : strings.o

# target to build an object file
strings.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/strings.c.o
.PHONY : strings.c.o

strings.i: strings.c.i

.PHONY : strings.i

# target to preprocess a source file
strings.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/strings.c.i
.PHONY : strings.c.i

strings.s: strings.c.s

.PHONY : strings.s

# target to generate assembly for a file
strings.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/strings.c.s
.PHONY : strings.c.s

vwm.o: vwm.c.o

.PHONY : vwm.o

# target to build an object file
vwm.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/vwm.c.o
.PHONY : vwm.c.o

vwm.i: vwm.c.i

.PHONY : vwm.i

# target to preprocess a source file
vwm.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/vwm.c.i
.PHONY : vwm.c.i

vwm.s: vwm.c.s

.PHONY : vwm.s

# target to generate assembly for a file
vwm.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/vwm.c.s
.PHONY : vwm.c.s

vwm_panel.o: vwm_panel.c.o

.PHONY : vwm_panel.o

# target to build an object file
vwm_panel.c.o:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/vwm_panel.c.o
.PHONY : vwm_panel.c.o

vwm_panel.i: vwm_panel.c.i

.PHONY : vwm_panel.i

# target to preprocess a source file
vwm_panel.c.i:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/vwm_panel.c.i
.PHONY : vwm_panel.c.i

vwm_panel.s: vwm_panel.c.s

.PHONY : vwm_panel.s

# target to generate assembly for a file
vwm_panel.c.s:
	$(MAKE) -f CMakeFiles/vwm.dir/build.make CMakeFiles/vwm.dir/vwm_panel.c.s
.PHONY : vwm_panel.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... vwm"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... bkgd.o"
	@echo "... bkgd.i"
	@echo "... bkgd.s"
	@echo "... clock.o"
	@echo "... clock.i"
	@echo "... clock.s"
	@echo "... hotkeys.o"
	@echo "... hotkeys.i"
	@echo "... hotkeys.s"
	@echo "... mainmenu.o"
	@echo "... mainmenu.i"
	@echo "... mainmenu.s"
	@echo "... modules.o"
	@echo "... modules.i"
	@echo "... modules.s"
	@echo "... poll_input_thd.o"
	@echo "... poll_input_thd.i"
	@echo "... poll_input_thd.s"
	@echo "... private.o"
	@echo "... private.i"
	@echo "... private.s"
	@echo "... profile.o"
	@echo "... profile.i"
	@echo "... profile.s"
	@echo "... settings.o"
	@echo "... settings.i"
	@echo "... settings.s"
	@echo "... signals.o"
	@echo "... signals.i"
	@echo "... signals.s"
	@echo "... sleep_thd.o"
	@echo "... sleep_thd.i"
	@echo "... sleep_thd.s"
	@echo "... strings.o"
	@echo "... strings.i"
	@echo "... strings.s"
	@echo "... vwm.o"
	@echo "... vwm.i"
	@echo "... vwm.s"
	@echo "... vwm_panel.o"
	@echo "... vwm_panel.i"
	@echo "... vwm_panel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

